kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: intra-namespace
  namespace: freeforall
spec:
  podSelector:
    ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              name: freeforall