apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test
  name: test
  namespace: test
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - a
            - b
        topologyKey: kubernetes.io/hostname
  containers:
  - image: test
    imagePullPolicy: IfNotPresent
    name: test
  imagePullSecrets:
  - name: test