apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/iam-role-we-created
  name: my-serviceaccount
  namespace: default
secrets:
- name: my-serviceaccount-token