apiVersion: v1
kind: Service
metadata:  
  labels:
    app: test
  name: test-service
  namespace: test01
spec:  
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: test
  type: ClusterIP