apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-master
  namespace: database
spec:
  ports:
  - name: redis
    nodePort: 36379
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app: redis
    role: master
  type: NodePort