apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    app: test
    # pv.kubernetes.io/bind-completed: "yes"
    # pv.kubernetes.io/bound-by-controller: "yes"
  name: efs-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  # need to create storage class for this and controller for efs first
  storageClassName: efs-sc
  volumeMode: Filesystem
  volumeName: efs-pv