# permissions for end users to view jobwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jobwatcher-viewer-role
rules:
- apiGroups:
  - batch.insomniacoder.github.com
  resources:
  - jobwatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.insomniacoder.github.com
  resources:
  - jobwatchers/status
  verbs:
  - get
