apiVersion: v1
kind: Pod
metadata:
  labels:
    app: debug-tools
  name: debug
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: alpine
    name: debug-tools
  hostNetwork: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - "ip-10-xx-xx-xx.eu-west-1.compute.internal"